export const ADD_DECISION = 'ADD_DECISION';
export const REMOVE_DECISION = 'REMOVE_DECISION';
export const REMOVE_DECISIONS = 'REMOVE_DECISIONS';
export const UPDATE_DECISION = 'UPDATE_DECISION';
export const RESET_DECISION = 'RESET_DECISION';
export const ADD_ATTRIBUTE = 'ADD_ATTRIBUTE';
export const RESET_ATTRIBUTE = 'RESET_ATTRIBUTE';
export const REMOVE_ATTRIBUTE = 'REMOVE_ATTRIBUTE';
export const UPDATE_ATTRIBUTE = 'UPDATE_ATTRIBUTE';
export const UPLOAD_RULESET = 'UPLOAD_RULESET';
export const UPLOAD_DBRULESET = 'UPLOAD_DBRULESET';

export const ADD_RULESET = 'ADD_RULESET';
export const UPDATE_RULESET_INDEX = 'UPDATE_RULESET_INDEX';
export const UPDATE_NAV_STATE = 'UPDATE_NAV_STATE';
export const LOG_IN = 'LOG_IN';

export const SEARCH_RID_DB = 'SEARCH_RID_DB'

export const ADD_DEBUG = 'ADD_DEBUG';
export const RESET_DEBUG = 'RESET_DEBUG';
export const REMOVE_DEBUG = 'REMOVE_DEBUG';
export const UPDATE_DEBUG = 'UPDATE_DEBUG';


export const ADD_ALLRULES_REDUX = 'ADD_ALLRULES_REDUX';

export const LOAD_RULE_TYPES = 'LOAD_RULE_TYPES';




